### ISSUE TITLE
Minor issues: Open to See.

### ISSUE THREAD

**Issue by Seemii** [Seemii/test#261]
Issue 1: Time on the strip is not right when u challenge someone. it is something like 75388d
Issue 2: Timer is set to 00:00 as default when we come into the game before accepting a challenge
Issue 3: Waiting for accept clock looks like it is moving

**Comment by nkhawaja1** [comment]
[FIXED] Issue 1: Time on the strip is not right when u challenge someone. it is something like 75388d
[FIXED] Issue 2: Timer is set to 00:00 as default when we come into the game before accepting a challenge
[FIXED] Issue 3: Waiting for accept clock looks like it is moving
