### ISSUE TITLE
The following message listeners must call this code, right on top to protect from invalid message handling. This is being handled in the game listeners but not the gamebet listeners.

### ISSUE THREAD

**Issue by Seemii** [Seemii/test#5]
File name: GSService_Messages.cs

Code to call:
if (!IsCurrentChallenge(message.Data.GetString(GSBackendKeys.CHALLENGE_ID)))
                {
                    return;
                }

Listeners:
 ChallengeWonMessage.Listener += OnChallengeWonMessage;
            ChallengeLostMessage.Listener += OnChallengeLostMessage;
            ChallengeDrawnMessage.Listener += OnChallengeDrawnMessage;

**Comment by nkhawaja1** [comment]
You can close this issue
