### ISSUE TITLE
During game if internet disconnects, no message displayed "No internet connection"

### ISSUE THREAD

**Issue by Seemii** [Seemii/test#79]
Steps:

1. Disconnect the internet during game.
2. Loading sign appears only

**Comment by nkhawaja1** [comment]
The game will no longer display an internet disconnection or other detailed error messages. On an error the game will halt and show an error code in which case the game app will have to be restarted. 
If the internet connection fails but there is no error then Connecting screen will display. On a successful reconnection when the internet connection is restored, the game will start from the Lobby.
